# Generated by Django 2.2.4 on 2020-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantItem', '0001_initial'),
        ('RestaurantMenu', '0002_auto_20200525_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='menu_included', to='RestaurantItem.Item'),
        ),
    ]
