# Generated by Django 2.2.4 on 2020-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantLogin', '0001_initial'),
        ('RestaurantMenu', '0003_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ManyToManyField(related_name='menus', to='RestaurantLogin.Restaurant'),
        ),
    ]
