# Generated by Django 2.2.4 on 2020-05-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantLogin', '0003_auto_20200527_0028'),
        ('RestaurantMenu', '0004_menu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='menus', to='RestaurantItem.Item'),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='RestaurantLogin.Restaurant'),
            preserve_default=False,
        ),
    ]
