# Generated by Django 2.2.4 on 2020-05-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMenu', '0005_auto_20200527_0028 2'),
        ('RestaurantMenu', '0005_auto_20200527_0028'),
    ]

    operations = [
    ]
