# Generated by Django 2.2.4 on 2020-05-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantEvent', '0002_auto_20200524_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='spots_available',
            field=models.IntegerField(),
        ),
    ]
