# Generated by Django 2.2.4 on 2020-05-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMenu', '0001_initial'),
        ('RestaurantEvent', '0003_auto_20200524_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_included', to='RestaurantMenu.Menu'),
            preserve_default=False,
        ),
    ]
