# Generated by Django 2.2.4 on 2020-05-26 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantLogin', '0002_auto_20200526_1839'),
        ('RestaurantEvent', '0005_event_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='spots_available',
            new_name='maximum_orders',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='minimum_amount_per_order',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='minimum_orders',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(default='notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='restaurant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_events', to='RestaurantLogin.Restaurant'),
            preserve_default=False,
        ),
    ]
