# Generated by Django 2.2.4 on 2020-05-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
        ('RestaurantLogin', '0002_auto_20200526_1839'),
        ('RestaurantEvent', '0006_auto_20200526_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Location.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='RestaurantLogin.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='RestaurantMenu.Menu'),
        ),
    ]
