# Generated by Django 2.2.4 on 2020-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantEvent', '0007_auto_20200527_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='In Progress', max_length=30),
            preserve_default=False,
        ),
    ]
