# Generated by Django 2.2.4 on 2020-05-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserOrder', '0001_initial'),
        ('Messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='UserOrder.Order'),
            preserve_default=False,
        ),
    ]
