# Generated by Django 2.2.4 on 2020-05-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantLogin', '0002_auto_20200526_1839'),
        ('RestaurantItem', '0003_auto_20200526_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='RestaurantLogin.Restaurant'),
            preserve_default=False,
        ),
    ]
