# Generated by Django 2.2.4 on 2020-05-27 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantItem', '0004_auto_20200527_0028'),
        ('UserLogin', '0001_initial'),
        ('RestaurantEvent', '0007_auto_20200527_0028'),
        ('UserOrder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='RestaurantEvent.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(related_name='orders', to='RestaurantItem.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='UserLogin.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='RestaurantItem.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='UserOrder.Order'),
            preserve_default=False,
        ),
    ]
